### ISSUE TITLE
Provide information about data collection and how to disable it

### ISSUE THREAD

**Issue by mbrukman** [Microsoft/spring-data-gremlin#135]
The section [Data/Telemetry in the `README.md`][readme-telemetry] says:

> This project collects usage data and sends it to Microsoft to help improve our products and services. Read our privacy statement to learn more.

However, the words `privacy statement` are not a link and do not point anywhere, nor is there another link to the privacy statement.

Also, [a search for the word `privacy` in this repo][search-privacy] shows no mention other than the word in the sentence above, from the `README.md` itself.

Thus, it is unclear:

* **what** info is collected
* **where** this info is sent
* **how** to disable it

Alternatively, why not disable it by default and allow users to opt-in to sharing this information?

[readme-telemetry]: https://github.com/Microsoft/spring-data-gremlin/blob/5e015b0641ac251095c711c76d477eb8876a4664/README.md#datatelemetry
[search-privacy]: https://github.com/Microsoft/spring-data-gremlin/search?q=privacy&unscoped_q=privacy

**Comment by Incarnation-p-lee** [comment]
@mbrukman 
Thanks for interesting spring-data-gremlin. In fact, we use telemetry to collect the information like repo name, version or something like that. We will update privacy link in readme and clear the way of disable telemetry in configuration. You can simply disable telemetry  as following:
```
gremlin:
  endpoint: url-of-endpoint 
  port: 443
  username: /dbs/your-db-name/colls/your-collection-name
  password: your-password
  telemetryAllowed: false
```
